apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cosmotech-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cosmotech-api.labels" . | nindent 4 }}
  annotations:
    email: "platform@cosmotech.com"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
  {{- with .Values.deploymentStrategy }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cosmotech-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        networking/traffic-allowed: "yes"
        {{- include "cosmotech-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imageCredentials.registry }}
      imagePullSecrets:
        - name: {{ include "cosmotech-api.fullname" . }}-registry
      {{- end }}
{{/*      {{- with .Values.imagePullSecrets }}*/}}
{{/*      imagePullSecrets:*/}}
{{/*        {{- toYaml . | nindent 8 }}*/}}
{{/*      {{- end }}*/}}
      serviceAccountName: {{ include "cosmotech-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: tmp-dir
          emptyDir: {}
        - name: helm-config
          secret:
            secretName: {{ include "cosmotech-api.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            #
            # Some env vars here are properties that affect the way the Spring Application Context
            # is configured.
            # They need to be set here *before* the Application Context starts
            #
            - name: CSM_PLATFORM_VENDOR
              # Used to include a specific '{{ .Values.config.csm.platform.vendor }}' Spring profile
              value: "{{ .Values.config.csm.platform.vendor }}"
            {{if .Values.config.csm.platform.identityProvider }}
            - name: IDENTITY_PROVIDER
            # Used to include a specific '{{ .Values.config.csm.platform.identityProvider.code | default "azure" }}' Spring profile
              value: {{ .Values.config.csm.platform.identityProvider.code | quote }}
            {{end}}
            - name: SPRING_PROFILES_INCLUDE
              # The properties file for the 'helm' profile is mounted as a Volume in the Container,
              # using a configured Kubernetes Secret containing all the 'config.*' properties
              value: "helm"
          volumeMounts:
            - mountPath: /tmp
              name: tmp-dir
              readOnly: false
            - mountPath: /config
              name: helm-config
              readOnly: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: http-management
              containerPort: 8081
              protocol: TCP
          startupProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 60
            tcpSocket:
              port: http
          livenessProbe:
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 2
            httpGet:
              path: /actuator/health/liveness
              port: http-management
          readinessProbe:
            timeoutSeconds: 5
            httpGet:
              path: /actuator/health/readiness
              port: http-management
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
      {{- if .Values.affinity}}
      {{- with .Values.affinity }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app.kubernetes.io/name"
                      operator: In
                      values:
                        - {{ include "cosmotech-api.name" . }}
                    - key: "app.kubernetes.io/instance"
                      operator: In
                      values:
                        - {{ .Release.Name }}
                topologyKey: "kubernetes.io/hostname"
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
